import type { Metadata } from "next";
import "@/styles/globals.css";
import localFont from "next/font/local";
import Header from "@/components/Header";

// NanumSquare 폰트 설정
const nanumSquare = localFont({
  src: [
    {
      path: "../fonts/NanumSquareR.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/NanumSquareB.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/NanumSquareEB.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-nanumSquare",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${nanumSquare.variable}`}>
      <head>
        {/* 로고 favicon 설정 */}
        <link rel="icon" href="/images/favicon.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${nanumSquare.className} mx-auto overflow-hidden bg-gray-50`}
      >
        {/* 페이지 상단에 위치할 Header 컴포넌트 */}
        <Header />
        {/* 자식 컴포넌트 렌더링 */}
        {children}
      </body>
    </html>
  );
}
